window.PATTERN_APP_DATA = {
  patterns: {
    "The Hidden Pattern Hunter": { summary: "You notice the structures, habits, and repeated behaviours that others miss.", description: "You are drawn to what sits underneath the surface of a group experience. While others focus on the activity itself, you notice the repeated moves, avoided topics, power patterns, emotional rhythms, and unspoken rules shaping what happens.\n\nYou use play as a way to make those patterns visible. A game, card, map, metaphor, or strange prompt gives people enough distance to say, “Ah, we do this all the time.”", strength: "You help groups see what is already happening, but has not yet been named.", danger: "You may spot the pattern faster than the group is ready to see it. If you move too quickly, people may feel analysed rather than invited.", next: "Ask: “Where have we seen this pattern before?”", pairings: "You work especially well with The Trust Builder, who creates enough safety for the pattern to be explored, and The Ripple Mapper, who helps the group see what the pattern causes.", bridge: "nnherit playkits are built to help groups notice hidden dynamics without turning the conversation into blame." },
    "The Gentle Rule Breaker": { summary: "You use play to make difficult things easier to say.", description: "You are good at creating just enough disruption to shift a conversation out of politeness, habit, or avoidance. You might introduce an unusual question, a strange rule, a role reversal, or a playful constraint that lets people say something they would normally soften or hide.\n\nYou do not break rules for shock value. You break the small invisible rules that keep a group stuck.", strength: "You open honest conversations without making the room feel unsafe.", danger: "You may soften the disruption so much that the real issue stays hidden, or push too quickly before trust is strong enough.", next: "Ask: “What rule are we following here that no one has named?”", pairings: "You work especially well with The Trust Builder, who protects the emotional space, and The Pressure Keeper, who helps the group stay with what has been opened.", bridge: "nnherit uses structured disruption to help people talk about sensitive issues indirectly, safely, and productively." },
    "The Game Maker": { summary: "You turn messy situations into rules, roles, moves, and meaningful choices.", description: "You naturally see how a complex situation could become playable. You take something vague, emotional, or tangled and give it structure. You create roles, rounds, cards, turns, constraints, choices, and simple rules that help people engage without getting lost.\n\nFor you, a good game is not just fun. It gives people a temporary system where they can test behaviour, notice consequences, and try new moves.", strength: "You make complexity easier to enter by giving people a clear structure to play inside.", danger: "You may over-design the activity. If the rules become too clever or too complex, the game can start serving itself rather than the conversation.", next: "Ask: “What is the smallest rule that would make this situation playable?”", pairings: "You work especially well with The Debrief Alchemist, who helps people make meaning afterwards, and The Fast Tester, who keeps the design light and iterative.", bridge: "nnherit turns complex human and business dynamics into playable systems that people can explore together." },
    "The Debrief Alchemist": { summary: "You help people turn activity into insight and insight into action.", description: "You know that the real value of play often comes after the game. You listen for what shifted, what surprised people, what became visible, and what the experience means beyond the activity itself.\n\nYou help groups move from “that was interesting” to “this tells us something useful.” You are especially strong at asking questions that connect play to real behaviour, decisions, relationships, or future action.", strength: "You help people extract meaning without flattening the experience into a lesson too quickly.", danger: "You may spend too long in reflection and lose energy. Some groups need a sharper move from insight to action.", next: "Ask: “What did the activity make easier to see?”", pairings: "You work especially well with The Game Maker, who creates rich experiences to debrief, and The Ripple Mapper, who helps connect insights to wider consequences.", bridge: "nnherit playkits are designed not only for activity, but for structured reflection, sense-making, and transfer." },
    "The Pressure Keeper": { summary: "You help groups stay with productive tension instead of escaping too quickly.", description: "You understand that some of the most useful learning happens in the space between comfort and discomfort. You do not rush to rescue the group, solve the issue, or make everyone feel better too soon.\n\nYou use play to hold tension at the right distance. A role, card, metaphor, or scenario can keep difficult material in the room without making it personal too quickly.", strength: "You help groups stay with what matters long enough for real insight to emerge.", danger: "You may underestimate how much support some people need before they can stay with tension productively.", next: "Ask: “What are we trying to move away from too quickly?”", pairings: "You work especially well with The Trust Builder, who keeps the group safe, and The Gentle Rule Breaker, who helps surface the tension in the first place.", bridge: "nnherit helps groups explore tension through structured play, rather than avoiding it or confronting it too directly." },
    "The Trust Builder": { summary: "You create enough safety for people to take part, take risks, and be honest.", description: "You pay close attention to the conditions that allow people to play seriously. You notice who is holding back, who may feel exposed, and whether the group has enough clarity, permission, and emotional safety to enter the activity.\n\nYou know that playful work is not automatically safe. It needs framing, boundaries, choice, care, and respect.", strength: "You make participation feel possible, especially for people who are cautious, sceptical, or unsure.", danger: "You may protect the room so much that it never becomes challenging enough to create movement.", next: "Ask: “What would make this feel safe enough to try, but still meaningful?”", pairings: "You work especially well with The Gentle Rule Breaker, who brings the challenge, and The Pressure Keeper, who helps the group stay with it.", bridge: "nnherit uses playful distance to make sensitive conversations safer without removing their seriousness." },
    "The What-If Spinner": { summary: "You open new possibilities through surprise, imagination, and reframing.", description: "You are drawn to possibility. When a group is trapped in familiar thinking, you introduce a new angle, a strange prompt, a random card, a speculative scenario, or a playful “what if” that changes the field.\n\nYou help people loosen their grip on the obvious answer. Your play style creates room for imagination, alternative futures, and unexpected combinations.", strength: "You help groups escape fixed thinking and discover options they could not see before.", danger: "You may generate too many possibilities without helping the group choose, test, or apply one.", next: "Ask: “What would become possible if we changed one rule?”", pairings: "You work especially well with The Fast Tester, who turns possibility into experiments, and The Ripple Mapper, who explores what each possibility might cause.", bridge: "nnherit uses playful scenarios and prompts to help people imagine alternatives before they are forced into decisions." },
    "The Perspective Jumper": { summary: "You help people step into different roles, positions, and viewpoints.", description: "You instinctively understand that people often get stuck inside their own view. You use role play, characters, stakeholder positions, masks, cards, or perspective shifts to help them see from somewhere else.\n\nYou do not ask people only what they think. You ask them to try on how a situation might look from another seat.", strength: "You reduce defensiveness by moving the conversation away from fixed personal positions.", danger: "You may create perspective shifts that are interesting but not connected clearly enough to the real decision or relationship.", next: "Ask: “Who sees this completely differently, and what would they say?”", pairings: "You work especially well with The Hidden Pattern Hunter, who spots repeated roles, and The Debrief Alchemist, who helps translate the role shift into insight.", bridge: "nnherit uses characters, roles, and archetypes to help people explore difficult dynamics without pointing directly at individuals." },
    "The Room Shifter": { summary: "You change the energy of a group through pace, movement, rhythm, or humour.", description: "You can feel the room. You notice when energy drops, when attention scatters, when the group becomes too stiff, or when people need to move before they can think differently.\n\nYou use small changes in pace, rhythm, posture, movement, humour, or interaction to reset the group. For you, play is not only cognitive. It is physical, social, and energetic.", strength: "You help groups move out of stuck states and into a more alive, responsive mode.", danger: "You may shift energy without giving enough time for meaning, reflection, or transfer.", next: "Ask: “What does the room need now: movement, silence, speed, or space?”", pairings: "You work especially well with The Debrief Alchemist, who helps make sense of the shift, and The Trust Builder, who ensures energy does not become pressure.", bridge: "nnherit treats play as an embodied and social way to change how people enter complex conversations." },
    "The Swarm Weaver": { summary: "You activate collective intelligence and help groups think together.", description: "You are interested in what the group can know, sense, or create together. You design participation so ideas do not depend only on the loudest person, the most senior person, or the first suggestion.\n\nYou use rounds, signals, small groups, shared mapping, parallel thinking, and simple structures to let intelligence emerge across the room.", strength: "You help groups access more of what they collectively know.", danger: "You may trust emergence so much that the group lacks enough direction, decision, or closure.", next: "Ask: “What simple structure would let everyone contribute one useful signal?”", pairings: "You work especially well with The Game Maker, who creates simple rules for contribution, and The Ripple Mapper, who helps connect the group’s ideas into a wider picture.", bridge: "nnherit playkits help groups build shared understanding through structured participation, not expert instruction alone." },
    "The Fast Tester": { summary: "You push people to try, prototype, fail lightly, and learn quickly.", description: "You do not like conversations that stay abstract for too long. You want people to make a first version, test an idea, try a move, run a small experiment, or learn by doing.\n\nYou use play to lower the cost of failure. A game, prototype round, rough sketch, or trial move helps people act before they overthink.", strength: "You turn hesitation into movement and help groups learn from real attempts.", danger: "You may move into action before the group has understood the deeper pattern, risk, or emotional context.", next: "Ask: “What is the smallest safe version we could test now?”", pairings: "You work especially well with The What-If Spinner, who generates options to test, and The Hidden Pattern Hunter, who notices what the test reveals.", bridge: "nnherit uses playful artefacts to help people experiment with different moves before they make real-world decisions." },
    "The Ripple Mapper": { summary: "You help people see consequences, second-order effects, and wider system impact.", description: "You naturally look beyond the first move. When a group makes a choice, you ask what it affects, who feels it, what it changes, what it triggers, and what might happen next.\n\nYou use maps, scenarios, cards, chains, clusters, and consequence prompts to help people see how one decision travels through a system.", strength: "You help groups make wiser choices by seeing beyond the immediate moment.", danger: "You may make the system feel so complex that people become cautious, slow, or overwhelmed.", next: "Ask: “If we make this move, what changes next, and who feels it first?”", pairings: "You work especially well with The Game Maker, who makes complexity playable, and The Pressure Keeper, who helps the group stay with uncomfortable consequences.", bridge: "nnherit playkits help groups map how behaviours, decisions, and tensions move through a wider system." }
  },
  shared: {
    cta: "Download the complete Play Pattern Field Guide PDF for all 12 patterns and practical prompts for using play with groups.",
    disclaimer: "This is not a personality test or diagnostic tool. It is a playful reflection prompt designed to help you notice how you tend to use play in group settings.",
    fieldGuidePdfUrl: "field-guide.pdf"
  },
  questions: [
    { q: "A team keeps repeating the same meeting conflict. You first...", options: [
      { text: "Map the repeated dynamic and name the pattern.", primary: "The Hidden Pattern Hunter", secondary: "The Ripple Mapper" },
      { text: "Shift one invisible rule so the truth can surface.", primary: "The Gentle Rule Breaker", secondary: "The Trust Builder" },
      { text: "Turn the issue into a playable format with clear roles.", primary: "The Game Maker", secondary: "The Fast Tester" }
    ]},
    { q: "A workshop feels polite but superficial. You...", options: [
      { text: "Introduce a provocative but safe constraint.", primary: "The Gentle Rule Breaker", secondary: "The Pressure Keeper" },
      { text: "Reframe through a perspective role swap.", primary: "The Perspective Jumper", secondary: "The Trust Builder" },
      { text: "Change rhythm with movement and quick pair rounds.", primary: "The Room Shifter", secondary: "The Swarm Weaver" }
    ]},
    { q: "After an engaging activity, people say 'That was fun.' You...", options: [
      { text: "Debrief for insight and real-world transfer.", primary: "The Debrief Alchemist", secondary: "The Ripple Mapper" },
      { text: "Ask for one immediate test action.", primary: "The Fast Tester", secondary: "The Debrief Alchemist" },
      { text: "Gather collective signals before closing.", primary: "The Swarm Weaver", secondary: "The Game Maker" }
    ]},
    { q: "Your client wants innovation but avoids risk. You...", options: [
      { text: "Run tiny, low-stakes experiments quickly.", primary: "The Fast Tester", secondary: "The What-If Spinner" },
      { text: "Generate alternate futures through speculative prompts.", primary: "The What-If Spinner", secondary: "The Ripple Mapper" },
      { text: "Hold tension instead of rushing to comfort.", primary: "The Pressure Keeper", secondary: "The Trust Builder" }
    ]},
    { q: "The room has mixed seniority and voices are uneven. You...", options: [
      { text: "Design equal-turn structures and parallel input.", primary: "The Swarm Weaver", secondary: "The Trust Builder" },
      { text: "Use stakeholder cards to shift viewpoint.", primary: "The Perspective Jumper", secondary: "The Hidden Pattern Hunter" },
      { text: "Set a simple game loop for fair participation.", primary: "The Game Maker", secondary: "The Swarm Weaver" }
    ]},
    { q: "Energy drops midway through a serious session. You...", options: [
      { text: "Reset with movement, pace, and social rhythm.", primary: "The Room Shifter", secondary: "The Trust Builder" },
      { text: "Introduce a playful what-if to unlock curiosity.", primary: "The What-If Spinner", secondary: "The Room Shifter" },
      { text: "Pause and ask what tension is being avoided.", primary: "The Pressure Keeper", secondary: "The Hidden Pattern Hunter" }
    ]},
    { q: "A group needs psychological safety before hard topics. You...", options: [
      { text: "Clarify boundaries, consent, and pacing.", primary: "The Trust Builder", secondary: "The Gentle Rule Breaker" },
      { text: "Use indirect play tools for safer entry.", primary: "The Gentle Rule Breaker", secondary: "The Trust Builder" },
      { text: "Start with a shared systems map, not personal blame.", primary: "The Ripple Mapper", secondary: "The Hidden Pattern Hunter" }
    ]},
    { q: "You hear one strong proposal. Your instinct is to...", options: [
      { text: "Test a rough version before committing.", primary: "The Fast Tester", secondary: "The Game Maker" },
      { text: "Ask what second-order effects it could trigger.", primary: "The Ripple Mapper", secondary: "The Pressure Keeper" },
      { text: "Ask whose perspective is missing.", primary: "The Perspective Jumper", secondary: "The Swarm Weaver" }
    ]},
    { q: "Complexity is overwhelming the group. You...", options: [
      { text: "Build a simple playable structure.", primary: "The Game Maker", secondary: "The Debrief Alchemist" },
      { text: "Identify recurring behaviour patterns first.", primary: "The Hidden Pattern Hunter", secondary: "The Game Maker" },
      { text: "Hold the key tension and slow the rush to solutions.", primary: "The Pressure Keeper", secondary: "The Debrief Alchemist" }
    ]},
    { q: "You close a high-stakes facilitation sprint by...", options: [
      { text: "Naming what shifted and what it means next.", primary: "The Debrief Alchemist", secondary: "The Ripple Mapper" },
      { text: "Asking what one rule-change could open now.", primary: "The What-If Spinner", secondary: "The Gentle Rule Breaker" },
      { text: "Designing one collective contribution round.", primary: "The Swarm Weaver", secondary: "The Room Shifter" }
    ]}
  ]
};
